name: PR Tests

on:
  pull_request:
    branches:
      - main
      - 'release/**'

jobs:
  pr-tests:
    uses: CitrineInformatics/common-gh-actions/.github/workflows/run-tests.yml@v2
    with:
      src: gemd
      skip_38: true
      include_313: true
