name: PR Tests

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - main
      - 'release/**'

jobs:
  pr-tests:
    uses: CitrineInformatics/common-gh-actions/.github/workflows/run-tests.yml@v1.1
    with:
      src: gemd
      skip_38: true
      include_313: true
